### ISSUE TITLE
Provincial (ON) tax brackets incorrectly set

### ISSUE THREAD

**Issue by kamalsaleh2** [bean-counter/bean-counter#13]
https://www.canada.ca/en/revenue-agency/services/tax/individuals/frequently-asked-questions-individuals/canadian-income-tax-rates-individuals-current-previous-years.html?wbdisable=true

**Comment by kamalsaleh2** [comment]
From link above:


5.05% on the first $42,960 of taxable income, +9.15% on the next $42,963, +11.16% on the next $64,077, +12.16% on the next $70,000, +13.16 % on the amount over $220,000
--





5.05% - 0==>42,960
9.15% - 42,960==>85,923
11.16% - 85,923==> 150,000
12.16% - 150,000==>220,000
13.16% - 220,000==> Inf.

**Comment by JackNeto** [comment]
@kamalsaleh2 these numbers are for 2018

**Comment by kamalsaleh2** [comment]
@JackNeto I thought we were using 2018 numbers because the Federal numbers we currently show are for 2018. We need to be consistent there. 

2018 - Federal + Provincial: https://www.canada.ca/en/revenue-agency/services/tax/individuals/frequently-asked-questions-individuals/canadian-income-tax-rates-individuals-current-previous-years.html?wbdisable=true

2017-Federal: https://www.canada.ca/en/financial-consumer-agency/services/financial-toolkit/taxes/taxes-2/5.html

**Comment by JackNeto** [comment]
I think we currently have the 2016 numbers, but because for this year people are still filing taxes we still need the numbers for 2017 but I'll also add the 2018 ones and provide a way to change the Tax year

**Comment by kamalsaleh2** [comment]
Federal is currently using 2018 numbers (unless I'm looking at the wrong place, or 2018=2016 fed. taxes
